name: Run a notebook in databricks

on:
 push:
  branches:
    - main

jobs:
 run-databricks-notebook:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repo
       uses: actions/checkout@v2
     - name: Run a databricks notebook
       uses: databricks/run-notebook@v0
       with:
         local-notebook-path: Preprocessing.py
         databricks-host: https://adb-5817605248122673.13.azuredatabricks.net
         databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
         new-cluster-json: >
           {
             "num_workers": 1,
             "spark_version": "13.3.x-scala2.12",
             "node_type_id": "Standard_D3_v2"
           }